[package]
name = "dme"
version = "0.1.0"
edition = "2024"
authors = ["CryptoPatrick <cryptopatrick@gmail.com>"]

###############################################################################
description = ""Dialogue Move Engine""
documentation = "https://docs.rs/dme"
homepage = "https://github.com/cryptopatrick/dme"
repository = "https://github.com/cryptopatrick/dme"
readme = "README.md"
keywords = ["<KEYWORD1>", "<KEYWORD2>" ]
license = "MIT"
autotests = false

###############################################################################
[lib]
name = "dme"
path = "src/lib.rs"

[[test]]
name = "tests"
path = "tests/test.rs"

###############################################################################
[dependencies]
